### PR TITLE
Favourites funcionality/feature/#6

### LINKED ISSUE #14: Make favourite funcionality

### PR DESCRIPTION
**Pull request by drmodun**
closes #14 
This branch implements favourite funcionality, which uses the backend to store user specific favourites, deployed at vercel, now it is finally time for reviews

### CODE REVIEW

**Comment by drmodun** [comment]
the reason of this abnormally large amount of file changes is because this merges the user branch as well, so most files are not actually new

**Comment by ilovric00** [comment]
@drmodun merge conflict first, before review

**Comment by ilovric00** [comment]
@drmodun conflicts first please 🙂

**Comment by drmodun** [comment]
Yea I will solve confilicts when I merge 5 with 4 so I do not create more confilcts

**Pull request merged**
